version: '3'
services:
  app:
    container_name: wafer2
    build: .
    command: "npm start"
    ports:
      - '3001:3001'
    volumes:
      - "../:/app/"
      - "/app/node_modules"
    restart: always
